name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Sanity import check
        run: |
          python - <<'PY'
          import importlib
          import sys
          try:
              importlib.import_module('main_automation')
          except Exception as e:
              print('Import failed:', e)
              sys.exit(1)
          print('Import ok')
          PY
      - name: Uvicorn dry-run
        run: |
          python - <<'PY'
          try:
              from uvicorn.config import Config
              from uvicorn.server import Server
              Config('main_automation:app')
              print('Uvicorn config ok')
          except Exception as e:
              print('Uvicorn config failed:', e)
              raise
          PY
